#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "immich"
name = "Immich"
description.en = "Photo and video backup solution directly from your mobile phone"
description.fr = "Sauvegarde de photos et de vidéos directement depuis votre mobile"

version = "1.98.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "free" # you can see the available licenses identifiers list here: https://spdx.org/licenses/
website = "https://immich.app"
demo = "https://demo.immich.app"
admindoc = "https://immich.app/docs/overview/introduction"
userdoc = "https://immich.app/docs/overview/introduction"
code = "https://github.com/immich-app/immich"


# FIXME: optional but recommended (or remove if irrelevant / not applicable).
# This is meant to be an URL where people can financially support this app, especially when its development is based
# on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.
fund = "https://liberapay.com/alex.tran1502"
fund = "https://github.com/sponsors/immich-app"
fund = "https://www.buymeacoffee.com/altran1502"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

# FIXME: replace with true, false, or "not_relevant".
# Not to confuse with the "sso" key: the "ldap" key corresponds to wether or not a user *can* login on the app using
# its YunoHost credentials.
ldap = false

sso = false

disk = "50M"
ram.build = "4G"
ram.runtime = "4G"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/immich"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

  [resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/immich-app/immich/archive/refs/tags/v1.98.0.tar.gz"
    sha256 = "0e09d833560dd6ed2c1b339ff3fdebde2c620e490e49bac582cf8169d394f047"
    in_subdir = true
    
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = [ "uploads" ]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    web.default = 3000
    server.default = 3001
    microservices.default = 3002
    mlearning.default = 3003

    [resources.apt]
    packages = "ffmpeg, python3-venv, python3-dev,"

    [resources.database]
    type = "potsgresql"
