packaging_format = 2

id = "photoprism"
name = "Photoprism"
description.en = "AI-Powered Photos App for the Decentralized Web"
description.fr = "Gestion de photos en ligne"

version = "2023.10.21~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0-only"
website = "https://photoprism.app"
demo = "https://demo-fr.photoprism.app"
admindoc = "https://docs.photoprism.app/developer-guide/"
userdoc = "https://docs.photoprism.app/user-guide/"
code = "https://github.com/photoprism/photoprism"
fund = "https://www.photoprism.app/membership"

[integration]
yunohost = ">= 11.2.3"
architectures = ["amd64", "i386"]
multi_instance = true
ldap = true
sso = "true"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/"

    [install.init_main_permission]
    help.en = "If enabled, Photoprism will be accessible by mobile apps and by users without a YunoHost account. This can be changed later in the webadmin."
    help.fr = "Si cette case est cochée, Photoprism sera accessible par des applications mobiles et par les utilisateurs n’ayant pas de compte YunoHost. Vous pourrez changer cela dans la webadmin."
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["french", "english"]
    default = "french"

    #[install.admin]
    #type = "user"

    [install.password]
    help.en = "Photoprism currently supports only one user : admin. Choose a password here."
    help.fr = "Photoprism ne permet qu'un seul utilisateur pour le moment. Choisissez un mot de passe ici."
    type = "password"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]

        [resources.sources.main]
        amd64.url = "https://github.com/Thovi98/test_ynh/releases/download/2023-10-21/photoprism-231028-9abea5b55-linux-amd64.tar.gz"
        amd64.sha256 = "2a1f2dcc70a94baf3ceaa6b7187d6a2517d6f360a1d2d979bd04ee928429a830"
        # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    sharing.url = "/s"
    sharing.allowd = "visitors"
    sharing.show_tile = false
    sharing.protected = true

    [resources.ports]
    main.default = 2342

    [resources.apt]
    packages = "ffmpeg, exiftool, libimage-exiftool-perl, libpng-dev, libjpeg-dev, libtiff-dev, imagemagick, darktable, mariadb-server"

    [resources.database]
    type = "mysql"
