#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status "$app-server" >/dev/null; then
    ynh_script_progression --message="Removing $app-server service integration..." --weight=1
    yunohost service remove "$app-server"
fi

if ynh_exec_warn_less yunohost service status "$app-machine-learning" >/dev/null; then
    ynh_script_progression --message="Removing $app-machine-learning service integration..." --weight=1
    yunohost service remove "$app-machine-learning"
fi

if ynh_exec_warn_less yunohost service status "$app-microservices" >/dev/null; then
    ynh_script_progression --message="Removing $app-microservices service integration..." --weight=1
    yunohost service remove "$app-microservices"
fi

ynh_remove_logrotate

ynh_remove_systemd_config

ynh_remove_nginx_config

ynh_secure_remove --file="/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
